### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by Ben348** [MattJeanes/MuteIndicator#2]
When will you release support for Mac?

**Comment by AmyJeanes** [comment]
I will never

**Comment by tidusjar** [comment]
+1
Please reopen

**Comment by LaurenceNairne** [comment]
+1 I don't even use a Mac and I want this supported. Please reopen.

**Comment by sophia-ma** [comment]
I am also interested +1

**Comment by bendotpw** [comment]
Is there an update on when this feature is likely to be completed?

**Comment by tidusjar** [comment]
I'm using this in my company and we are moving to Mac, so this is holding up our rollout.

**Comment by bendotpw** [comment]
Bump

**Comment by tidusjar** [comment]
I also am waiting for this. Is there an ETA

**Comment by tidusjar** [comment]
bump

**Comment by AmyJeanes** [comment]
It doesn't work sorry 
![image](https://user-images.githubusercontent.com/2363642/114221414-37180600-9965-11eb-9d5a-a5bc9022cfe1.png)

**Comment by tidusjar** [comment]
Please fix then

**Comment by AmyJeanes** [comment]
If you would like to donate me a computer running macOS I could investigate further

**Comment by LaurenceNairne** [comment]
How did you see this issue without a Mac?

**Comment by AmyJeanes** [comment]
Well that's just it I didn't

**Comment by LaurenceNairne** [comment]
Great, you fixed the issue 🙂

Please forward the expected release date.

**Comment by AmyJeanes** [comment]
You misunderstand sir I told my friend Toby to run it

**Comment by LaurenceNairne** [comment]
Pass on my congratulations to your dear friend Toby on his success in
fixing the issue.

If you could get him to update us on release timelines it would be greatly
appreciated.

**Comment by AmyJeanes** [comment]
No Sir please understand the issue is not fixed, I require expensive Mac computer
